# Generated by Django 3.1.1 on 2020-10-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0003_auto_20200927_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='purpose',
        ),
        migrations.AddField(
            model_name='account',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='answer',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='guide',
            name='question',
            field=models.CharField(max_length=100),
        ),
    ]
