# Generated by Django 3.1.1 on 2020-10-04 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0007_question_answer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='LegalAspectsOfBusiness',
        ),
    ]
