# Generated by Django 3.1.1 on 2020-10-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0010_personnelmanagement'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeTax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.PositiveIntegerField(null=True)),
                ('question', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
